---
abstract: 'A slacked web application framework based on Plack'
author:
  - 'robario <webmaster@robario.com>'
build_requires: {}
configure_requires:
  Module::Build: '0.3800'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Slack
provides:
  Slack:
    file: lib/Slack.pm
    version: v0.10.1
  Slack::Action:
    file: lib/Slack/Action.pm
    version: v0.1.1
  Slack::App:
    file: lib/Slack/App.pm
    version: v0.6.3
  Slack::Context:
    file: lib/Slack/Context.pm
    version: v0.3.1
  Slack::Controller:
    file: lib/Slack/Controller.pm
    version: v0.9.1
  Slack::Request:
    file: lib/Slack/Request.pm
    version: v0.3.4
  Slack::Response:
    file: lib/Slack/Response.pm
    version: v0.2.3
  Slack::Util:
    file: lib/Slack/Util.pm
    version: v0.2.5
requires:
  Plack: '0'
resources:
  license: http://dev.perl.org/licenses/
version: v0.10.1
